#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fann
Version  : d71d54788bee56ba4cf7522801270152da5209d7
Release  : 5
URL      : https://github.com/libfann/fann/archive/d71d54788bee56ba4cf7522801270152da5209d7.tar.gz
Source0  : https://github.com/libfann/fann/archive/d71d54788bee56ba4cf7522801270152da5209d7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : AGPL-3.0 BSD-3-Clause LGPL-2.1
Requires: fann-lib
BuildRequires : cmake

%description
# Fast Artificial Neural Network Library
## FANN
**Fast Artificial Neural Network (FANN) Library** is a free open source neural network library, which implements multilayer artificial neural networks in C with support for both fully connected and sparsely connected networks.

%package dev
Summary: dev components for the fann package.
Group: Development
Requires: fann-lib
Provides: fann-devel

%description dev
dev components for the fann package.


%package lib
Summary: lib components for the fann package.
Group: Libraries

%description lib
lib components for the fann package.


%prep
%setup -q -n fann-d71d54788bee56ba4cf7522801270152da5209d7

%build
mkdir clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -flto -O3 -fno-semantic-interposition -falign-functions=32 "
export FCFLAGS="$CFLAGS -flto -O3 -fno-semantic-interposition -falign-functions=32 "
export FFLAGS="$CFLAGS -flto -O3 -fno-semantic-interposition -falign-functions=32 "
export CXXFLAGS="$CXXFLAGS -flto -O3 -fno-semantic-interposition -falign-functions=32 "
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DLIB_SUFFIX=64
make V=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/cmake/fann/fann-config.cmake
/usr/lib64/cmake/fann/fann-use.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/*.hpp
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
