#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fann
Version  : 2.2.0
Release  : 1
URL      : https://github.com/libfann/fann/archive/2.2.0.tar.gz
Source0  : https://github.com/libfann/fann/archive/2.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: fann-lib
BuildRequires : cmake

%description
Fast Artificial Neural Network Library (FANN)
Fast Artificial Neural Network Library is a free open source neural network
library, which implements multilayer artificial neural networks in C with
support for both fully connected and sparsely connected networks.
Cross-platform execution in both fixed and floating point are supported.
It includes a framework for easy handling of training data sets. It is easy to
use, versatile, well documented, and fast. Bindings to more than 15 programming
languages are available. An easy to read introduction article and a reference
manual accompanies the library with examples and recommendations on how to use
the library. Several graphical user interfaces are also available for the
library.

%package dev
Summary: dev components for the fann package.
Group: Development
Requires: fann-lib
Provides: fann-devel

%description dev
dev components for the fann package.


%package lib
Summary: lib components for the fann package.
Group: Libraries

%description lib
lib components for the fann package.


%prep
%setup -q -n fann-2.2.0

%build
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir}
make V=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib/*.so.*
